### ISSUE TITLE
skipToNextItem() produces PLAY_ACTIVITY error

### ISSUE THREAD

**Issue by logangeorge01** [zachomedia/apple-music-webplayer#106]
When I press the button to skip songs, it consistently logs this error. It seems like it's a MusicKit issue because it seems to be plaguing all other Apple Music web players. It's not super consequential, other than it kinda glitches out and occasionally produces some audio hiccups. I just wondered if there's any way of avoiding this error, as I'm trying to use the MusitKit functionality on my own website.

Uncaught (in promise) PLAY_ACTIVITY: A play stop() method was called without a previous play() descriptor
at Function.MKError.playActivityError (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:25498)
at PlayActivity. (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:36354)
at https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:14473
at Object.next (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:14578)
at https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:13494
at new Promise ()
at __awaiter (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:13229)
at PlayActivity.stop (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:35849)
at PlayActivity. (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:33878)
at https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:14473
at Object.next (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:14578)
at https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:13494
at new Promise ()
at __awaiter (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:13229)
at PlayActivity.exit (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:33788)
at HTMLDocument. (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:163084)
at HTMLDocument.r (https://musi.sh/app.47281733.js:53:16771)

**Comment by zachomedia** [comment]
Yeah, this is very likely a MusicKit JS bug since I only call `instance.player.skipToNextItem();` (https://github.com/zachomedia/apple-music-webplayer/blob/master/src/store/modules/musicKit.js#L428) in order to switch to the next track.

Have you tried opening a support request with Apple through https://feedbackassistant.apple.com/welcome?

**Comment by logangeorge01** [comment]
Yeah, I've done that, so I'll reply when I get a response from them.

**Comment by logangeorge01** [comment]
Apple has fixed the bug.
