### ISSUE TITLE
Random error on playlist play

### ISSUE THREAD

**Issue by T3kstiil3** [zachomedia/apple-music-webplayer#58]
Sometime playlist stop playing on next song and log this errors:

```
Uncaught (in promise) DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at Buffer.get [as endBufferedTime] (https://js-cdn.music.apple.com/musickit/v1/musickit.js:13:124407)
    at https://js-cdn.music.apple.com/musickit/v1/musickit.js:13:126279
    at new Promise (<anonymous>)
    at https://js-cdn.music.apple.com/musickit/v1/musickit.js:13:126215
    at Buffer.<anonymous> (https://js-cdn.music.apple.com/musickit/v1/musickit.js:13:125856)
    at https://js-cdn.music.apple.com/musickit/v1/musickit.js:13:14390
    at Object.next (https://js-cdn.music.apple.com/musickit/v1/musickit.js:13:14495)
    at https://js-cdn.music.apple.com/musickit/v1/musickit.js:13:13411
    at new Promise (<anonymous>)
    at __awaiter (https://js-cdn.music.apple.com/musickit/v1/musickit.js:13:13146)
    at Buffer.dequeueBufferAction (https://js-cdn.music.apple.com/musickit/v1/musickit.js:13:125622)
    at SourceBuffer.i (https://music.zacharyseguin.ca/static/js/vendor.e775b0f607ff1d577284.js:12:31208)
```

```
musickit.js:13 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request. https://goo.gl/LdLk22
```

Navigator: Chrome Version 67.0.3396.99 (Build officiel) (32 bits) / Windows
Not tested on my mac

**Comment by T3kstiil3** [comment]
I think the real error was :
```
Uncaught (in promise) DOMException: Rejected with system code (44) https://music.zacharyseguin.ca/playlists/pl.pm-20e9f373919da0802ef601a8fb596094
```
